### PR TITLE
Define xrange() for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
xrange() was removed from Python 3 in favor of range().

### CODE REVIEW

**Comment by yotam** [comment]
Hi, thanks for the PR. In other files we're using the `six` library for this, [as in this example](https://github.com/deepmind/dm_control/blob/e4cbf1897a61d12f66f4059137f3709aca1e7134/dm_control/mujoco/engine.py#L55). Would you mind updating the code here to match? Thanks!

**Comment by yotam** [comment]
Thanks, just one more nit before I merge: Could you move the six imports to the end of the import section, in both files? That will keep our linter happy internally. (We'll see if it's possible to run the checks automatically on GitHub.)

**Comment by cclauss** [comment]
Do you folks use [isort[(http://isort.readthedocs.io) or do you have a different approach?

**Comment by yotam** [comment]
We use a version of pylint. The import order is essentially: standard library imports (sorted alphabetically), then third party imports (sorted alphabetically).

**Pull request merged**
