### PR TITLE
Add initial gitignore

### PR DESCRIPTION
**Pull request by Capri2014**
Add initial gitignore to omit the .pyc files

### CODE REVIEW

**Comment by Capri2014** [comment]
Done

**Comment by wookayin** [comment]
Why not git.io/Python.gitignore?

**Comment by Capri2014** [comment]
@wookayin You are right, that should be a better idea. My initial thought was just seeing a lot of *.pyc while playing it and found it annoying

**Comment by Capri2014** [comment]
@wookayin after the second thought, Python.gitignore might be an overkill through

**Comment by alimuldal** [comment]
Manually merged in c24ec9f5f3cb3c25c6571c89c9f60bf3350f5711, thanks!

**Pull request closed without merging**
